# 1. 오케스트레이션 앱 (App)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parking-orchestration-app
spec:
  replicas: 2  # 고가용성과 HPA 설정을 고려해 2로 증설 권장
  selector:
    matchLabels:
      app: parking-orchestration-app
  template:
    metadata:
      labels:
        app: parking-orchestration-app
    spec:
      containers:
      - name: app
        image: hyungdongjo/parking-orchestration-app:latest
        ports:
        - containerPort: 8000

        # --- 리소스 제한 설정 추가 ---
        resources:
          requests:
            cpu: 100m      # HPA가 사용률을 계산하는 기준 (0.1 코어)
            memory: 256Mi
          limits:
            cpu: 300m      # 파드가 최대로 사용할 수 있는 한계
            memory: 512Mi
        # ----------------------------

        env:
        - name: DB_HOST
          value: "parking-db-orchestration-service"
        - name: DB_NAME
          valueFrom: { secretKeyRef: { name: parking-secret, key: orchestration_db_name } }
        - name: DB_USER
          valueFrom: { secretKeyRef: { name: parking-secret, key: username } }
        - name: DB_PASSWORD
          valueFrom: { secretKeyRef: { name: parking-secret, key: password } }
        - name: DJANGO_ALLOWED_HOSTS
          value: "*"
        - name: DJANGO_SECRET_KEY
          valueFrom: { secretKeyRef: { name: parking-secret, key: django_secret_key } }
        - name: VEHICLE_SERVICE_URL
          value: "http://parking-vehicle-app-service:80"
        - name: ZONE_SERVICE_URL
          value: "http://parking-zone-app-service:80"
        - name: COMMAND_SERVICE_URL
          value: "http://parking-command-app-service:80"
---
apiVersion: v1
kind: Service
metadata:
  name: parking-orchestration-app-service
spec:
  type: ClusterIP
  selector:
    app: parking-orchestration-app
  ports:
    - port: 80
      targetPort: 8000
