apiVersion: apps/v1
kind: Deployment
metadata:
  name: parking-orchestration-app
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: parking-orchestration-app
  template:
    metadata:
      labels:
        app: parking-orchestration-app
    spec:
      containers:
      - name: app
        image: hyungdongjo/parking-orchestration-app:latest
        ports:
        - containerPort: 8000

        resources:
          requests:
            cpu: 100m      
            memory: 256Mi
          limits:
            cpu: 300m      
            memory: 512Mi

        env:
        - name: ORCHESTRATION_DB_HOST
          value: "parking-db-orchestration-service"
        - name: ORCHESTRATION_DB_NAME
          valueFrom: { secretKeyRef: { name: parking-secret, key: orchestration_db_name } }
        - name: DB_USER
          valueFrom: { secretKeyRef: { name: parking-secret, key: username } }
        - name: DB_PASSWORD
          valueFrom: { secretKeyRef: { name: parking-secret, key: password } }
        - name: DJANGO_ALLOWED_HOSTS
          value: "*"
        - name: DJANGO_SECRET_KEY
          valueFrom: { secretKeyRef: { name: parking-secret, key: django_secret_key } }
        - name: VEHICLE_SERVICE_URL
          value: "http://parking-vehicle-app-service:80"
        - name: ZONE_SERVICE_URL
          value: "http://parking-zone-app-service:80"
        - name: COMMAND_SERVICE_URL
          value: "http://parking-command-app-service:80"
---
apiVersion: v1
kind: Service
metadata:
  name: parking-orchestration-app-service
spec:
  type: ClusterIP
  selector:
    app: parking-orchestration-app
  ports:
    - port: 80
      targetPort: 8000
