apiVersion: apps/v1
kind: Deployment
metadata:
  name: parking-query-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parking-query-grpc
  template:
    metadata:
      labels:
        app: parking-query-grpc
    spec:
      containers:
      - name: app
        image: hyungdongjo/parking-query-app:latest
        imagePullPolicy: Always
        command: ["/opt/venv/bin/python"]
        args: ["manage.py", "run_parking_query_grpc"]
        env:
        - name: PYTHONPATH
          value: "/app:/app/shared:/app/contracts/gen/python:/app/services/parking-query-service/src"
        - name: DJANGO_SETTINGS_MODULE
          value: "park_py.settings_parking_query"
        - name: PARKING_QUERY_DB_HOST
          value: "parking-query-db-service"
        - name: PARKING_QUERY_DB_NAME
          value: "parking_db"
        - name: PARKING_QUERY_DB_USER
          valueFrom: { secretKeyRef: { name: parking-db-secret, key: user-id } }
        - name: PARKING_QUERY_DB_PASSWORD
          valueFrom: { secretKeyRef: { name: parking-db-secret, key: user-password } }
        - name: VEHICLE_SERVICE_GRPC_TARGET
          value: "vehicle-grpc-service:50015"
        - name: ZONE_SERVICE_GRPC_TARGET
          value: "zone-grpc-service:50016"
---
apiVersion: v1
kind: Service
metadata:
  name: parking-query-grpc-service
spec:
  selector:
    app: parking-query-grpc
  ports:
    - protocol: TCP
      port: 50018
      targetPort: 50018
