apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle-grpc
  template:
    metadata:
      labels:
        app: vehicle-grpc
    spec:
      containers:
      - name: app
        image: hyungdongjo/parking-vehicle-app:latest
        imagePullPolicy: Always
        command: ["/opt/venv/bin/python"]
        args: ["manage.py", "run_vehicle_grpc"]
        env:
        - name: PYTHONPATH
          value: "/app:/app/shared:/app/contracts/gen/python:/app/services/vehicle-service/src"
        - name: DJANGO_SETTINGS_MODULE
          value: "park_py.settings_vehicle"
        - name: VEHICLE_DB_HOST
          value: "vehicle-db-service"
        - name: VEHICLE_DB_NAME
          value: "parking_db"
        - name: VEHICLE_DB_USER
          valueFrom: { secretKeyRef: { name: parking-db-secret, key: user-id } }
        - name: VEHICLE_DB_PASSWORD
          valueFrom: { secretKeyRef: { name: parking-db-secret, key: user-password } }
        - name: DJANGO_SECRET_KEY
          valueFrom: { secretKeyRef: { name: parking-secret, key: django_secret_key } }
---
apiVersion: v1
kind: Service
metadata:
  name: vehicle-grpc-service
spec:
  selector:
    app: vehicle-grpc
  ports:
    - protocol: TCP
      port: 50015
      targetPort: 50015
