apiVersion: apps/v1
kind: Deployment
metadata:
  name: zone-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zone-grpc
  template:
    metadata:
      labels:
        app: zone-grpc
    spec:
      containers:
      - name: app
        image: hyungdongjo/parking-zone-app:latest
        imagePullPolicy: Always
        command: ["/opt/venv/bin/python"]
        args: ["manage.py", "run_zone_grpc"]
        env:
        - name: PYTHONPATH
          value: "/app:/app/shared:/app/contracts/gen/python:/app/services/zone-service/src"
        - name: DJANGO_SETTINGS_MODULE
          value: "park_py.settings_zone"
        - name: ZONE_DB_HOST
          value: "zone-db-service"
        - name: ZONE_DB_NAME
          value: "parking_db"
        - name: ZONE_DB_USER
          valueFrom: { secretKeyRef: { name: parking-db-secret, key: user-id } }
        - name: ZONE_DB_PASSWORD
          valueFrom: { secretKeyRef: { name: parking-db-secret, key: user-password } }
---
apiVersion: v1
kind: Service
metadata:
  name: zone-grpc-service
spec:
  selector:
    app: zone-grpc
  ports:
    - protocol: TCP
      port: 50016
      targetPort: 50016
