apiVersion: v1
kind: PersistentVolume
metadata:
  name: parking-db-pv-volume  # PV의 고유 이름
spec:
  capacity:
    storage: 5Gi              # 사용자님이 PVC에서 요청한 5Gi와 똑같이 맞춤
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce           # 한 노드에서 읽기/쓰기 가능
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    # 워커 노드의 실제 폴더 경로
    path: /mnt/data/mariadb
