apiVersion: apps/v1
kind: Deployment
metadata:
  name: parking-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parking-bot
  template:
    metadata:
      labels:
        app: parking-bot
    spec:
      containers:
      - name: traffic-bot
        image: hyungdongjo/parking-bot:latest
        imagePullPolicy: Always
        env:
        - name: API_URL
          value: "http://orchestration-http:8000/api/v1/parking"
