apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: parking-command-db
spec:
  serviceName: "parking-command-db-service"
  replicas: 1
  selector:
    matchLabels:
      app: parking-command-db
  template:
    metadata:
      labels:
        app: parking-command-db
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.6
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: parking-db-secret
              key: root-password
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: parking-db-secret
              key: user-id
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: parking-db-secret
              key: user-password
        - name: MARIADB_DATABASE
          value: "parking_db"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-sql
        configMap:
          name: parking-db-init-config
          items:
          - key: "command-init.sql"
            path: "01-command.sql"

  volumeClaimTemplates:
  - metadata:
      name: mariadb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "manual"
      selector:
        matchLabels:
          app: parking-command-db
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: parking-command-db-service
spec:
  ports:
  - port: 3306
    name: mysql
  clusterIP: None
  selector:
    app: parking-command-db
