apiVersion: v1
kind: PersistentVolume
metadata:
  name: parking-db-command-pv 
  labels:
    type: command
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/mariadb-command
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: parking-db-query-pv 
  labels:
    type: query
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/mariadb-query
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: parking-db-zone-pv 
  labels:
    type: zone
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/mariadb-zone 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: parking-db-vehicle-pv 
  labels:
    type: vehicle
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/mariadb-vehicle
    
