apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: parking-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api/saga      # 1. 가장 구체적인 경로를 맨 위로!
        pathType: Prefix
        backend:
          service:
            name: parking-orchestration-app-service
            port:
              number: 80

      - path: /api           # 2. 그다음 일반 API 경로
        pathType: Prefix
        backend:
          service:
            name: parking-backend-service
            port:
              number: 80

      - path: /              # 3. 나머지는 프론트엔드
        pathType: Prefix
        backend:
          service:
            name: parking-frontend-service
            port:
              number: 80
